### ISSUE TITLE
Difference between index.js and nodealarmproxy.js

### ISSUE THREAD

**Issue by mhdawson** [entrocode/NodeAlarmProxy#13]
When I installed from npm it seemed that it was index.js that contained the functionality for the proxy.  So for my recent PR that is the file I updated.

Looking at the rest of the files in the project I see now that there are 2 files with what looks like content that is quite similar.

index.js and nodealarmproxy.js

So I'm wondering which one is the right one to be using.  If its nodealarmproxy.js I'll switch over and submit a similar PR to add the option to disable logging there as well.

**Comment by entrocode** [comment]
@mhdawson ooh, that's a good catch.  nodealarmproxy.js should be the file since the package.json uses it... i'll fix that and make sure I didn't miss anything from before

**Comment by erfinb** [comment]
I believe the removal of this may have caused an issue with the homebridge-evnisalink... could someone confirm. Even after changing the pointer to look at the nodealarmproxy.js file instead of the index.js file which was removed, something still seems wrong and is causing the homebridge to return not responding status for HomeKit... I am using iOS 11 on my iPhone, however the Apple TVs in the house are still running stable versions of iOS 10...
